# @format

BOT:
  OWNERS: ['692617937512562729']
  ADMINS: ['692617937512562729']

LINKS:
  SUPPORT: 'https://discord.gg/uY5BXAfd'
  MONGO_URI: ''

CLIENT:
  PREFIX: 'e'
  COLOR: '#FF0000'
  SHARDS: 1 #value must be 'auto' or <integer>
  PER_CLUSTER: 2 #value must be <integer>
  TOKEN: 'MTA5MzgyMDYyMjY1NzgxODY5NA.XXXGrfQUz.68CZtpz502XleaYP4e3qH7kO6hKFkr-m_ZZOPQ'
  TOPGGAUTH: ''
  VOTEURI: ''

MANAGER:
  PREFIX: ''
  COLOR: ''
  TOKEN: ''
