# @format

BOT:
  OWNERS: []
  ADMINS: []

LINKS:
  SUPPORT: ''
  MONGO_URI: ''

CLIENT:
  PREFIX: '%'
  COLOR: ''
  SHARDS: 1 #value must be 'auto' or <integer>
  PER_CLUSTER: 2 #value must be <integer>
  TOKEN: 'MTA5MzgyMDYyMjY1NzgxODY5NA.GrfQUz.68CZtpz502XleaYP4e3qH7kO6hKFkr-m_ZZOPQ'
  TOPGGAUTH: ''
  VOTEURI: ''

MANAGER:
  PREFIX: ''
  COLOR: ''
  TOKEN: ''
