# @format

BOT:
  OWNERS: []
  ADMINS: []

LINKS:
  SUPPORT: ""
  MONGO_URI: ""

CLIENT:
  PREFIX: "%"
  COLOR: ""
  SHARDS: 1 #value must be 'auto' or <integer>
  PER_CLUSTER: 2 #value must be <integer>
  TOKEN: ""
  TOPGGAUTH: ""
  VOTEURI: ""

MANAGER:
  PREFIX: ""
  COLOR: ""
  TOKEN: ""
